Background task handling
AcalaNetwork/subway pull request #115
Opened 2023-10-05 09:30 UTC by ermalkaleci

2023-10-05 09:31 UTC, ermalkaleci commented on src/integration_tests/merge_subscription.rs
> +    let ((addr, server), _extensions) = start_server(config).await.unwrap();
@xlc keeps extensions alive

2023-10-05 22:09 UTC, xlc commented on src/server.rs
> +pub async fn start_server(config: Config) -> anyhow::Result<((SocketAddr, ServerHandle), TypeRegistryRef)> {
```suggestion
pub async fn start_server(config: Config) -> anyhow::Result<(SocketAddr, ServerHandle, TypeRegistryRef)> {
```

2023-10-05 22:11 UTC, xlc requested changes
need tests

2023-10-06 10:49 UTC, xlc approved these changes

2023-10-06 11:06 UTC, merged